# Generated by Django 5.2.16 on 2026-08-01 16:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Admin User",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("pathfinder", "Pathfinder"),
                            ("enabler", "Enabler"),
                            ("connection", "Connection"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("entity_id", models.CharField(db_index=True, max_length=64)),
                ("note_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="adminpanel.adminuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("suspend", "Suspend"),
                            ("reinstate", "Reinstate"),
                            ("edit_profile", "Edit Profile"),
                            ("update_connection_status", "Update Connection Status"),
                            ("send_message", "Send Message"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "target_entity_type",
                    models.CharField(
                        choices=[
                            ("pathfinder", "Pathfinder"),
                            ("enabler", "Enabler"),
                            ("connection", "Connection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_entity_id", models.CharField(db_index=True, max_length=64)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="adminpanel.adminuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BroadcastMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("all_pathfinders", "All Pathfinders"),
                            ("all_enablers", "All Enablers"),
                            ("all_users", "All Users"),
                            ("custom_segment", "Custom Segment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("segment_filter", models.JSONField(blank=True, null=True)),
                ("subject", models.CharField(max_length=200)),
                ("message_body", models.TextField()),
                ("recipient_count", models.IntegerField(default=0)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_by_admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcasts",
                        to="adminpanel.adminuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
