# Generated by Django 5.2.16 on 2026-08-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_database", "0011_emailverification_last_resend_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_suspended",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
