# Generated by Django 5.2.16 on 2026-07-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0004_alter_opportunity_opportunity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="target_applicants",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
